### PR TITLE
Update el.po

### PR DESCRIPTION
**Pull request by skarmoutsosv**
Full, fine-tuned, greek translation.

### CODE REVIEW

**Comment by twaugh** [comment]
Thanks!

We take translations from [Zanata](https://fedora.zanata.org/iteration/view/system-config-printer/master) so, rather than merge this PR and lose the translations next time I pull from Zanata, I uploaded your el.po to Zanata first and pulled new translations in.

**Comment by skarmoutsosv** [comment]
It could be better if I my commit was flagged as 'merged' and not as 'closed'.

**Comment by twaugh** [comment]
It wasn't a git merge. Zanata handled the msgid/msgstr merging. From the point of view of git, this was a straight pull from Zanata.

**Comment by skarmoutsosv** [comment]
I daily use Debian and I contribute greek translations using transifex.com, translationproject.org, l10n.gnome.org and launchpad.net
How can I contribute to system-config-printer at fedora.zanata.org? Currently it does not accept edits and a red lock with the message "The project-version is read only. It cannot be edited." appears.

**Comment by twaugh** [comment]
@skarmoutsosv That's weird. What's your Fedora Account System username?

**Comment by skarmoutsosv** [comment]
skarmoutsosv

**Comment by twaugh** [comment]
I think you have to [join a language team](http://docs.zanata.org/en/latest/user-guide/languages/language-team/index.html#join-a-language-team) first.

**Pull request closed without merging**
