### PR TITLE
landscape.io fixes

### PR DESCRIPTION
**Pull request by Spacil**

### CODE REVIEW

**Comment by twaugh** [comment]
The changes look good other than the PrintTestPage.py note.

**Comment by twaugh** [comment]
PS. If you're new to GitHub: you can commit further changes and they'll show up here automatically.

Thanks for looking at fixing the landscape.io problems!

**Comment by twaugh** [comment]
@Spacil Do you plan on adding more fixes or is this ready to merge?

**Comment by Spacil** [comment]
I think it's ready to merge, maybe I will add more fixes, but not this month.

**Comment by twaugh** [comment]
OK, merging. Thanks for starting on this!

**Comment by Spacil** [comment]
I'm happy that can be a part of the system.

**Pull request merged**
