### PR TITLE
Code refactoring of newprinter.py

### PR DESCRIPTION
**Pull request by mariospr**
This a refactoring of newprinter.py in an attempt to make the code more readable and, hopefully, more hackable too. The main changes done in this branch are of two types:
  * Use constants for page numbers instead of bare numbers
  * Refactoring of too big functions into smaller ones. Still not perfect, but a step forward
  
On top of that, I've also included a small fix for download_gpg_fingerprint() at the beginning of this PR, please let me know if you'd rather have it in a separate branch, or feel free to cherry pick it before the merge.

### CODE REVIEW

**Comment by twaugh** [comment]
@jpopelka Not sure if you'll get a chance to look at this before I do.

**Comment by jpopelka** [comment]
Outstanding work @mariospr :+1: 
It looks sooo much better now.

@twaugh LGTM

**Comment by mariospr** [comment]
> Outstanding work @mariospr :+1: 
> It looks sooo much better now.

Thank you, I appreciate your comments a lot!

I know it's still far from perfect, but at least it helped me a lot to understand the flow there.

**Comment by twaugh** [comment]
Thanks @mariospr!

**Pull request merged**
